"""
Rule Generator - LLM-powered NL rule generation
Falls back to keyword matching when no LLM available
"""

import json
import os
import re as _re
from llm.client import call_llm, extract_json
from llm.prompts import RULE_SYSTEM, RULE_USER


def _map_type(raw: str) -> str:
    r = (raw or "").lower().strip()
    mapping = {
        "not_null": "completeness", "null_check": "completeness",
        "completeness": "completeness", "missing": "completeness",
        "unique": "uniqueness", "uniqueness": "uniqueness", "duplicate": "uniqueness",
        "freshness": "freshness", "timeliness": "freshness", "stale": "freshness",
        "validity": "validity", "regex": "validity", "format": "validity",
        "range": "validity", "email": "validity", "pattern": "validity",
        "schema": "schema", "conformity": "schema", "structure": "schema",
        "anomaly": "anomaly", "outlier": "anomaly", "zscore": "anomaly",
    }
    return mapping.get(r, r if r in ["completeness","uniqueness","freshness","validity","schema","anomaly"] else "validity")

def _map_dimension(rule_type: str) -> str:
    dim_map = {
        "completeness": "completeness", "uniqueness": "uniqueness",
        "freshness": "timeliness", "validity": "validity",
        "schema": "conformity", "anomaly": "accuracy",
    }
    return dim_map.get(rule_type, "validity")

def _map_severity(raw: str) -> str:
    r = (raw or "").lower().strip()
    if r in ["critical", "high", "error", "urgent"]:
        return "critical"
    if r in ["warning", "medium", "moderate"]:
        return "warning"
    if r in ["info", "low", "minor"]:
        return "info"
    return "warning"


def _infer_from_prompt(prompt: str, config: dict) -> dict:
    """Post-process: infer min_value/max_value from prompt if LLM missed them."""
    p = prompt.lower()
    
    # "greater than X" / "positive"
    if "positive" in p and "min_value" not in config:
        config["min_value"] = 0
    gt = _re.search(r'(?:greater|more|above|over)\s+than\s+([\d.]+)', p)
    if gt and "min_value" not in config:
        config["min_value"] = float(gt.group(1))
    if "greater than zero" in p and "min_value" not in config:
        config["min_value"] = 0
    
    # "less than X" / "not exceed X"
    lt = _re.search(r'(?:less|below|under|not exceed|exceed)\s+([\d.]+)', p)
    if lt and "max_value" not in config:
        config["max_value"] = float(lt.group(1))
    if "not exceed 100" in p and "max_value" not in config:
        config["max_value"] = 100
    
    # "between X and Y"
    range_match = _re.search(r'between\s+([\d.]+)\s+and\s+([\d.]+)', p)
    if range_match:
        if "min_value" not in config:
            config["min_value"] = float(range_match.group(1))
        if "max_value" not in config:
            config["max_value"] = float(range_match.group(2))
    
    return config


def _detect_column(prompt: str, columns_info: str) -> str:
    """Try to detect column name from prompt."""
    p = prompt.lower()
    columns = []
    if columns_info:
        try:
            cols = json.loads(columns_info)
            columns = [c.get('name', '') for c in cols if isinstance(c, dict)]
        except:
            columns = [c.strip() for c in columns_info.split(',') if c.strip()]
    
    for col in columns:
        if col.lower() in p:
            return col
    # Try partial match
    for col in columns:
        col_words = col.lower().replace('_', ' ').split()
        for w in col_words:
            if len(w) > 3 and w in p:
                return col
    return ""


# ── Keyword fallback ──

def _keyword_generate(prompt: str, dataset_id: str, table_name: str, columns_info: str) -> dict:
    p = prompt.lower()
    
    rule_type = "validity"
    dimension = "validity"
    severity = "warning"
    config = {"autoGenerated": True}
    
    if any(w in p for w in ['null', 'empty', 'missing', 'blank', 'not null', 'not be null', 'should not be null']):
        rule_type = "completeness"
        dimension = "completeness"
    elif any(w in p for w in ['unique', 'duplicate', 'distinct', 'no duplicate']):
        rule_type = "uniqueness"
        dimension = "uniqueness"
    elif any(w in p for w in ['date', 'fresh', 'recent', 'stale', 'old', 'today', 'within']):
        rule_type = "freshness"
        dimension = "timeliness"
    elif any(w in p for w in ['schema', 'column', 'type', 'structure', 'exist']):
        rule_type = "schema"
        dimension = "conformity"
    
    if any(w in p for w in ['critical', 'urgent', 'important', 'high', 'must']):
        severity = "critical"
    elif any(w in p for w in ['info', 'low', 'minor', 'nice']):
        severity = "info"
    
    detected_col = _detect_column(prompt, columns_info)
    if detected_col:
        config["column"] = detected_col
    config["threshold"] = 95.0
    
    if 'email' in p or (detected_col and 'email' in detected_col.lower()):
        config["regex"] = "^[^@]+@[^@]+\\.[^@]+$"
    
    config = _infer_from_prompt(prompt, config)
    
    return {
        "name": f"Rule: {prompt[:60]}",
        "description": f"Generated from: {prompt}",
        "type": rule_type,
        "dimension": dimension,
        "severity": severity,
        "config": config,
        "datasetId": dataset_id,
        "generationMethod": "keyword",
    }


# ── LLM generate ──

def _llm_generate(prompt: str, dataset_id: str, table_name: str, columns_info: str) -> dict | None:
    user_prompt = RULE_USER.format(
        prompt=prompt,
        table_name=table_name or "unknown",
        columns=columns_info or "not available",
    )

    response = call_llm(RULE_SYSTEM, user_prompt, temperature=0.2)
    if not response:
        return None

    data = extract_json(response)
    if not data or not isinstance(data, dict):
        return None

    rule_type = _map_type(
        data.get("type") or data.get("rule_type") or data.get("check_type") or ""
    )
    
    raw_severity = data.get("severity") or data.get("priority") or ""
    severity = _map_severity(raw_severity)
    
    name = (
        data.get("name") or data.get("rule_name") or data.get("title")
        or f"Rule: {prompt[:60]}"
    )
    
    description = (
        data.get("description") or data.get("desc") or f"Generated from: {prompt}"
    )
    
    column = (
        data.get("column") or data.get("column_name") or data.get("field") or ""
    )
    
    # If LLM didn't find column, try to detect from prompt
    if not column:
        column = _detect_column(prompt, columns_info)
    
    threshold = data.get("threshold") or data.get("min_pass_rate") or 95.0
    if isinstance(threshold, str):
        try:
            threshold = float(str(threshold).replace("%", ""))
        except:
            threshold = 95.0
    
    config = {"autoGenerated": True}
    if column:
        config["column"] = column
    config["threshold"] = threshold
    
    # Copy config fields from LLM response
    for key in ["regex", "pattern", "min_value", "max_value", "expression", "format", "valid_values"]:
        if key in data and data[key] is not None:
            config[key] = data[key]
    
    # Post-process: infer missing min/max from prompt
    config = _infer_from_prompt(prompt, config)
    
    # If validity rule but no range/regex/valid_values, and we have min or max, that's fine
    # If we have neither, try to set based on prompt
    if rule_type == "validity" and "min_value" not in config and "max_value" not in config and "regex" not in config and "valid_values" not in config:
        # LLM gave us nothing useful - try harder
        config = _infer_from_prompt(prompt, config)
    
    return {
        "name": name,
        "description": description,
        "type": rule_type,
        "dimension": _map_dimension(rule_type),
        "severity": severity,
        "config": config,
        "datasetId": dataset_id,
        "generationMethod": "llm",
    }


# ── Main entry ──

def generate(prompt: str, dataset_id: str, table_name: str = "", columns_info: str = "") -> dict:
    api_key = os.environ.get("LLM_API_KEY", "")
    
    if api_key:
        result = _llm_generate(prompt, dataset_id, table_name, columns_info)
        if result:
            return result
    
    return _keyword_generate(prompt, dataset_id, table_name, columns_info)
